
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdd-webapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pdd-webapi
  template:
    metadata:
      labels:
        app: pdd-webapi
    spec:
      containers:
        - name: pdd-webapi
          image: felipefabricio/wdf.pedidos.webapi:latest
          ports:
            - containerPort: 8080
              name: pdd-webapi
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /_health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /_ready
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 600
          resources:
            limits:
              cpu: "0.5"
              memory: "1Gi"
            requests:
              cpu: "0.1"
              memory: "256Mi"
          env:
            - name: MYSQL_CONNECTION
              valueFrom:
                secretKeyRef:
                  name: mysql-connection-secret
                  key: connectionString
      imagePullSecrets:
        - name: dockerhub-secret

---

apiVersion: v1
kind: Service
metadata:
  name: pdd-webapi-service
spec:
  type: LoadBalancer
  selector:
    app: pdd-webapi
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pdd-webapi-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pdd-webapi
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
