name: CD Pipeline

on:
  push:
    branches:
      - master
      
jobs:
  CD:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Efetua Login no Azure
        uses: Azure/login@v1.6.1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'

      - name: Instalação do kubectl
        uses: azure/setup-kubectl@v2.0
        with:
          version: 'v1.29.1'
        id: install

      - name: Login no DockerHub
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build, Tag e Push da Imagem para o DockerHub
        run: |
          docker build -t felipefabricio/wonderfood:latest -f Dockerfile .
          docker push felipefabricio/wonderfood:latest               

      - name: Configuração do Context Kubernetes no Azure
        run: az aks get-credentials --resource-group wonderfood-rg --name wonderfood-cluster

      - name: Deploy do Manifesto no AKS
        run: kubectl apply -f deployment.yml